### ISSUE TITLE
Deprecation warning when accessing input_array of mpi plan

### ISSUE THREAD

**Issue by ultimanet** [fredRos/pyFFTW#3]
Accessing an input_array of a mpi plan creates a deprecation warning. The following code 

```
import pyfftw
import numpy as np
p = pyfftw.create_mpi_plan(input_shape=(6,6), input_dtype=np.complex, output_dtype=np.complex, direction='FFTW_FORWARD')
p.input_array
```

returns
`using a non-integer number instead of an integer will result in an error in the future`

I was not able to debug this completely, but it could be that the array access here contains floats:
https://github.com/fredRos/pyFFTW/blob/mpi/pyfftw/mpi.pxi#L1269

**Comment by fredRos** [comment]
I cannot reproduce the warning. Which version of python and numpy do you use? The arguments in the line you mentioned as well as in the line above are all reported to be of type `int` or `numpy.unit64`

**Comment by ultimanet** [comment]
Checked again and gone with version 1.13.0.
