### ISSUE TITLE
Creating MPI plan fails for input_shape (11, 1) on 3 nodes. 

### ISSUE THREAD

**Issue by ultimanet** [fredRos/pyFFTW#8]
Run the following code with `mpirun -n 3`

```
import numpy as np
import pyfftw

p = pyfftw.create_mpi_plan(input_shape=(11,1),
                           input_dtype=np.complex,
                           output_dtype=np.complex,
                           direction='FFTW_FORWARD',
                           flags=['FFTW_ESTIMATE'])
```

This raises

> Traceback (most recent call last):                                                                                                                               
>          File "pyfftw_debugging.py", line 44, in <module>                                                                                                               
>            flags=['FFTW_ESTIMATE'])                                                                                                                                     
>          File "pyfftw/mpi.pxi", line 922, in pyfftw.pyfftw.create_mpi_plan (/tmp/pyFFTW/pyfftw/pyfftw.c:21947)                                                          
>          File "pyfftw/mpi.pxi", line 1687, in pyfftw.pyfftw.FFTW_MPI.__cinit__ (/tmp/pyFFTW/pyfftw/pyfftw.c:29076)                                                      
>        RuntimeErrorRuntimeError: The data configuration has an uncaught error that led to FFTW returning an invalid plan in MPI rank 1.Please report this as a bug.

**Comment by fredRos** [comment]
I guess the error message is misleading. I think this transform is just not implemented in FFTW with mpi. It's effectively 1D, and for 1D only composite sizes are allowed, see
http://fftw.org/fftw3_doc/One_002ddimensional-distributions.html#One_002ddimensional-distributions

So in 1D you need at least a product of prime numbers! The docs are spread out, this seems to be the relevant bit

http://fftw.org/fftw3_doc/Complex-DFTs.html#Complex-DFTs

> FTW is best at handling sizes of the form 2a 3b 5c 7d 11e 13f, where e+f is either 0 or 1, and the other exponents are arbitrary. Other sizes are computed by means of a slow, general-purpose algorithm (which nevertheless retains O(n log n) performance even for prime sizes). It is possible to customize FFTW for different array sizes; see Installation and Customization. Transforms whose sizes are powers of 2 are especially fast.

but this applies to the non-MPI part of FFTW.

testing
-----

I updated your example like this

```python
input_shape=(16,1)
```

and it works fine. Making it truly 2D also works

```python
input_shape=(11,16)
```

Similar attempts that fail are other prime numbers

```python
input_shape=(2,1)
input_shape=(3,1)
input_shape=(5,1)
input_shape=(7,1)
input_shape=(13,1)
```

I have to think how to catch these problems with a more informative error message.

**Comment by fredRos** [comment]
Now I found the precise statement that this input shape is not supported with MPI. From http://fftw.org/fftw3_doc/MPI-Plan-Creation.html#MPI-Plan-Creation :

> For multi-dimensional transforms, any dimensions > 1 are supported; for one-dimensional transforms, only composite (non-prime) n0 are currently supported (unlike the serial FFTW). Requesting an unsupported transform size will yield a NULL plan. (As in the serial interface, highly composite sizes generally yield the best performance.)

**Comment by fredRos** [comment]
I can catch the above problem with an informative error message but the (1,1) case just leads to a segfault 😒 

It's interesting that there is an `fftw_mpi_guru_dft`function in the stack trace but it is not documented and not available to call in the header `fftw3-mpi.h`. So perhaps the same functionality with the serial/threaded guru interface is there but we can't use it to perform transforms along certain axes with mpi

```
$ mpirun -n 2 python2.7 issue8.py  
*** Error in `python2.7': munmap_chunk(): invalid pointer: 0x0000000002a58340 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7fc43a5c67e5]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x1a8)[0x7fc43a5d3698]
/usr/lib/x86_64-linux-gnu/libfftw3.so.3(fftw_mkproblem_dft_d+0x1d)[0x7fc4228ff81d]
/usr/lib/x86_64-linux-gnu/libfftw3_mpi.so.3(+0xa6b5)[0x7fc4230f76b5]
/usr/lib/x86_64-linux-gnu/libfftw3.so.3(+0x248e7)[0x7fc4228f68e7]
/usr/lib/x86_64-linux-gnu/libfftw3.so.3(+0x24b84)[0x7fc4228f6b84]
/usr/lib/x86_64-linux-gnu/libfftw3.so.3(+0xf5638)[0x7fc4229c7638]
/usr/lib/x86_64-linux-gnu/libfftw3.so.3(fftw_mkapiplan+0x10e)[0x7fc4229c784e]
/usr/lib/x86_64-linux-gnu/libfftw3_mpi.so.3(fftw_mpi_plan_guru_dft+0x105)[0x7fc4230f2fb5]
/usr/lib/x86_64-linux-gnu/libfftw3_mpi.so.3(fftw_mpi_plan_many_dft+0x81)[0x7fc4230f3081]
/home/beaujean/workspace/pyfftw/pyfftw/pyfftw.so(+0x5ef81)[0x7fc423360f81]
```
