### ISSUE TITLE
pyfftw produces wrong results for array with shape (10, 1) on more than 2 nodes

### ISSUE THREAD

**Issue by ultimanet** [fredRos/pyFFTW#9]
The following code doesn't work for `comm.size > 2`

```
import numpy as np
from numpy.testing import assert_allclose
import pyfftw

p = pyfftw.create_mpi_plan(input_shape=(10,1),
                           input_dtype=np.complex,
                           output_dtype=np.complex,
                           direction='FFTW_FORWARD',
                           flags=['FFTW_ESTIMATE'])

p_inverse = pyfftw.create_mpi_plan(input_shape=(10,1),
                           input_dtype=np.complex,
                           output_dtype=np.complex,
                           direction='FFTW_BACKWARD',
                           flags=['FFTW_ESTIMATE'])

np.random.seed(16)
a = np.random.random(p.input_array.shape) + \
    np.random.random(p.input_array.shape)*1j

p.input_array[:] = a
p()
p_inverse.input_array[:] = p.output_array
p_inverse()
assert_allclose(p_inverse.output_array, a)
```

**Comment by fredRos** [comment]
I even see a crash with 5 processes

```
mpirun -n 5 /usr/bin/python2.7 issue9.py
...
(mismatch 100.0%)
 x: array([[ -1.516131e+227 +3.790327e+226j],
       [  1.304430e+243 -3.790327e+226j]])
 y: array([[ 0.223291+0.550701j],
       [ 0.523163+0.045602j]])
*** Error in `/usr/bin/python2.7': free(): invalid size: 0x00000000018b51d0 ***
```

**Comment by fredRos** [comment]
But if I change the 2nd dim. from 1 -> 10, it works fine. So I guess it is related to #8 because the MWE is effectively 1D and FFTW has a different behavior then. I should call a different size function as mentioned here 
http://fftw.org/fftw3_doc/MPI-Data-Distribution-Functions.html#MPI-Data-Distribution-Functions

**Comment by fredRos** [comment]
From http://fftw.org/fftw3_doc/MPI-Plan-Creation.html#MPI-Plan-Creation

> For multi-dimensional transforms, any dimensions > 1 are supported;

so what you try isn't officially supported. Perhaps it works sometimes but you must not rely on it. I don't know how to work around that other than creating a lower dimensional copy of the array.

**Comment by fredRos** [comment]
catch all multidim. trafos where some dim is only 1D and raise an exception. This is unsupported by FFTW+MPI but doesn't always yield an invalid plan.
